apiVersion: v1
kind: Pod
metadata:
  name: p2pdinner-eureka-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: p2pdinner-eureka-service
    image: rajanikanthy/p2pdinner-eureka:latest
    ports:
    - containerPort: 8080 