apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-21T04:09:35Z
  generation: 2
  labels:
    app: p2pdinner-eureka-server
  name: p2pdinner-eureka-server
  namespace: default
  resourceVersion: "8155"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/p2pdinner-eureka-server
  uid: 1ed9134b-d4e7-11e8-96b1-42010a80003b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2pdinner-eureka-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: p2pdinner-eureka-server
    spec:
      containers:
      - image: gcr.io/glowing-vehicle-220016/p2pdinner-eureka-server:latest
        imagePullPolicy: Always
        name: p2pdinner-eureka-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-21T04:09:39Z
    lastUpdateTime: 2018-10-21T04:09:39Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
