apiVersion: v1
kind: Service
metadata:
  labels:
    app: p2pdinner-eureka-server
  name: p2pdinner-eureka-server-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8010
  selector:
    app: p2pdinner-eureka-server
  sessionAffinity: None
  type: LoadBalancer