name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: deploy-artifact
    - name: Compress
      uses: TonyBogdanov/zip@1.0
      with:
        args: zip -qq -r ./deploy-artifact.zip ./staging
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag config-server:$(date +%s)
